In [1]:
import numpy as np
import cv2
import math
import pandas as pd
from datetime import datetime
import datetime
from dateutil import relativedelta
import sys, csv ,operator

In [2]:
df = pd.read_csv("data_!.csv",delimiter=',')

In [3]:
d = int(input("Enter the date : "))
m = int(input("Enter the month : "))
yr = int(input("Enter the year : "))

Enter the date : 21
Enter the month : 3
Enter the year : 2008

In [35]:
dict = {1: 'Microwave', 5: 'Hall-Toilet door', 6: 'Hall-Bathroom door', 7: 'Cups cupboard', 8: 'Fridge', 9: 'Plates cupboard', 12: 'Frontdoor', 13: 'Dishwasher', 14: 'ToiletFlush', 17: 'Freezer', 18: 'Pans cupboard', 20: 'Washingmachine', 23: 'Groceries cupboard', 24: 'Hall-Bedroom door'}

In [36]:
dict[24]

'Hall-Bedroom door'

In [4]:
df['A'] = pd.to_datetime(df['start'])
df['B'] = pd.to_datetime(df['end'])
#df['time']=df['B'] - df['A']
df['time']=(df['A'] - df['B']) / np.timedelta64(-1, 'D')
df['time']=df['time']*86400
df['count']=0
df

,start,end,id,val,A,B,time,count
0,25-Feb-2008 0:20:14,25-Feb-2008 0:22:57,24,1,2008-02-25 00:20:14,2008-02-25 00:22:57,163.0,0
1,25-Feb-2008 9:33:41,25-Feb-2008 9:33:42,24,1,2008-02-25 09:33:41,2008-02-25 09:33:42,1.0,0
2,25-Feb-2008 9:33:47,25-Feb-2008 17:21:12,24,1,2008-02-25 09:33:47,2008-02-25 17:21:12,28045.0,0
3,25-Feb-2008 9:36:43,25-Feb-2008 9:37:04,5,1,2008-02-25 09:36:43,2008-02-25 09:37:04,21.0,0
4,25-Feb-2008 9:37:20,25-Feb-2008 9:37:23,6,1,2008-02-25 09:37:20,2008-02-25 09:37:23,3.0,0
5,25-Feb-2008 9:37:51,25-Feb-2008 9:37:52,14,1,2008-02-25 09:37:51,2008-02-25 09:37:52,1.0,0
6,25-Feb-2008 9:37:55,25-Feb-2008 9:37:56,14,1,2008-02-25 09:37:55,2008-02-25 09:37:56,1.0,0
7,25-Feb-2008 9:37:58,25-Feb-2008 9:38:01,6,1,2008-02-25 09:37:58,2008-02-25 09:38:01,3.0,0
8,25-Feb-2008 9:49:27,25-Feb-2008 9:49:28,9,1,2008-02-25 09:49:27,2008-02-25 09:49:28,1.0,0
9,25-Feb-2008 9:49:31,25-Feb-2008 9:49:38,9,1,2008-02-25 09:49:31,2008-02-25 09:49:38,7.0,0
10,25-Feb-2008 9:49:39,25-Feb-2008 9:49:44,8,1,2008-02-25 09:49:39,2008-02-25 09:49:44,5.0,0
11,25-Feb-2008 9:49:53,25-Feb-2008 9:49:56,8,1,2008-02-25 09:49:53,2008-02-25 09:49:56,3.0,0
12,25-Feb-2008 9:49:58,25-Feb-2008 9:50:04,1,1,2008-02-25 09:49:58,2008-02-25 09:50:04,6.0,0
13,25-Feb-2008 9:50:39,25-Feb-2008 9:50:42,23,1,2008-02-25 09:50:39,2008-02-25 09:50:42,3.0,0
14,25-Feb-2008 9:52:11,25-Feb-2008 9:53:21,1,1,2008-02-25 09:52:11,2008-02-25 09:53:21,70.0,0
15,25-Feb-2008 9:53:22,25-Feb-2008 9:53:25,23,1,2008-02-25 09:53:22,2008-02-25 09:53:25,3.0,0
16,25-Feb-2008 9:57:24,25-Feb-2008 10:01:27,13,1,2008-02-25 09:57:24,2008-02-25 10:01:27,243.0,0
17,25-Feb-2008 9:57:45,25-Feb-2008 9:58:29,9,1,2008-02-25 09:57:45,2008-02-25 09:58:29,44.0,0
18,25-Feb-2008 9:58:33,25-Feb-2008 9:58:34,18,1,2008-02-25 09:58:33,2008-02-25 09:58:34,1.0,0
19,25-Feb-2008 9:59:17,25-Feb-2008 9:59:18,7,1,2008-02-25 09:59:17,2008-02-25 09:59:18,1.0,0
20,25-Feb-2008 10:00:00,25-Feb-2008 10:00:04,9,1,2008-02-25 10:00:00,2008-02-25 10:00:04,4.0,0
21,25-Feb-2008 10:02:31,25-Feb-2008 10:02:54,5,1,2008-02-25 10:02:31,2008-02-25 10:02:54,23.0,0
22,25-Feb-2008 10:10:15,25-Feb-2008 10:10:16,5,1,2008-02-25 10:10:15,2008-02-25 10:10:16,1.0,0
23,25-Feb-2008 10:10:20,25-Feb-2008 17:00:28,5,1,2008-02-25 10:10:20,2008-02-25 17:00:28,24608.0,0
24,25-Feb-2008 10:19:28,25-Feb-2008 10:19:32,12,1,2008-02-25 10:19:28,2008-02-25 10:19:32,4.0,0
25,25-Feb-2008 16:54:37,25-Feb-2008 16:54:41,12,1,2008-02-25 16:54:37,2008-02-25 16:54:41,4.0,0
26,25-Feb-2008 16:59:04,25-Feb-2008 16:59:11,8,1,2008-02-25 16:59:04,2008-02-25 16:59:11,7.0,0
27,25-Feb-2008 16:59:14,25-Feb-2008 16:59:42,23,1,2008-02-25 16:59:14,2008-02-25 16:59:42,28.0,0
28,25-Feb-2008 16:59:48,25-Feb-2008 16:59:51,8,1,2008-02-25 16:59:48,2008-02-25 16:59:51,3.0,0
29,25-Feb-2008 17:00:33,25-Feb-2008 17:00:37,6,1,2008-02-25 17:00:33,2008-02-25 17:00:37,4.0,0
...,...,...,...,...,...,...,...,...
1199,21-Mar-2008 9:04:26,21-Mar-2008 17:03:51,24,1,2008-03-21 09:04:26,2008-03-21 17:03:51,28765.0,0
1200,21-Mar-2008 9:13:25,21-Mar-2008 9:13:29,6,1,2008-03-21 09:13:25,2008-03-21 09:13:29,4.0,0
1201,21-Mar-2008 9:14:19,21-Mar-2008 9:14:20,14,1,2008-03-21 09:14:19,2008-03-21 09:14:20,1.0,0
1202,21-Mar-2008 9:14:25,21-Mar-2008 9:15:18,6,1,2008-03-21 09:14:25,2008-03-21 09:15:18,53.0,0
1203,21-Mar-2008 9:17:57,21-Mar-2008 9:17:59,5,1,2008-03-21 09:17:57,2008-03-21 09:17:59,2.0,0
1204,21-Mar-2008 9:24:18,21-Mar-2008 9:24:19,5,1,2008-03-21 09:24:18,2008-03-21 09:24:19,1.0,0
1205,21-Mar-2008 9:24:23,21-Mar-2008 15:51:49,5,1,2008-03-21 09:24:23,2008-03-21 15:51:49,23246.0,0
1206,21-Mar-2008 9:42:35,21-Mar-2008 9:42:39,12,1,2008-03-21 09:42:35,2008-03-21 09:42:39,4.0,0
1207,21-Mar-2008 15:50:16,21-Mar-2008 15:50:20,12,1,2008-03-21 15:50:16,2008-03-21 15:50:20,4.0,0
1208,21-Mar-2008 15:52:04,21-Mar-2008 15:52:08,6,1,2008-03-21 15:52:04,2008-03-21 15:52:08,4.0,0
1209,21-Mar-2008 15:52:54,21-Mar-2008 15:52:55,14,1,2008-03-21 15:52:54,2008-03-21 15:52:55,1.0,0
1210,21-Mar-2008 15:52:54,21-Mar-2008 15:53:05,6,1,2008-03-21 15:52:54,2008-03-21 15:53:05,11.0,0
1211,21-Mar-2008 15:53:03,21-Mar-2008 15:53:11,5,1,2008-03-21 15:53:03,2008-03-21 15:53:11,8.0,0
1212,21-Mar-2008 15:54:06,21-Mar-2008 18:24:28,5,1,2008-03-21 15:54:06,2008-03-21 18:24:28,9022.0,0
1213,21-Mar-2008 15:57:07,21-Mar-2008 15:58:06,23,1,2008-03-21 15:57:07,2008-03-21 15:58:06,59.0,0
1214,21-Mar-2008 15:57:52,21-Mar-2008 15:57:56,8,1,2008-03-21 15:57:52,2008-03-21 15:57:56,4.0,0
1215,21-Mar-2008 17:03:54,21-Mar-2008 17:03:55,24,1,2008-03-21 17:03:54,2008-03-21 17:03:55,1.0,0
1216,21-Mar-2008 17:06:52,21-Mar-2008 17:06:53,24,1,2008-03-21 17:06:52,2008-03-21 17:06:53,1.0,0
1217,21-Mar-2008 17:06:57,21-Mar-2008 17:08:12,24,1,2008-03-21 17:06:57,2008-03-21 17:08:12,75.0,0
1218,21-Mar-2008 18:05:09,21-Mar-2008 18:05:10,24,1,2008-03-21 18:05:09,2008-03-21 18:05:10,1.0,0
1219,21-Mar-2008 18:24:31,21-Mar-2008 18:24:32,5,1,2008-03-21 18:24:31,2008-03-21 18:24:32,1.0,0
1220,21-Mar-2008 18:24:38,21-Mar-2008 18:24:39,5,1,2008-03-21 18:24:38,2008-03-21 18:24:39,1.0,0
1221,21-Mar-2008 18:24:50,21-Mar-2008 18:24:51,5,1,2008-03-21 18:24:50,2008-03-21 18:24:51,1.0,0
1222,21-Mar-2008 18:25:15,21-Mar-2008 18:25:16,6,1,2008-03-21 18:25:15,2008-03-21 18:25:16,1.0,0
1223,21-Mar-2008 18:27:46,21-Mar-2008 18:27:56,8,1,2008-03-21 18:27:46,2008-03-21 18:27:56,10.0,0
1224,21-Mar-2008 18:27:57,21-Mar-2008 18:27:58,8,1,2008-03-21 18:27:57,2008-03-21 18:27:58,1.0,0
1225,21-Mar-2008 18:28:00,21-Mar-2008 18:28:01,8,1,2008-03-21 18:28:00,2008-03-21 18:28:01,1.0,0
1226,21-Mar-2008 18:28:19,21-Mar-2008 18:28:20,17,1,2008-03-21 18:28:19,2008-03-21 18:28:20,1.0,0
1227,21-Mar-2008 19:11:10,21-Mar-2008 19:11:14,12,1,2008-03-21 19:11:10,2008-03-21 19:11:14,4.0,0
1228,23-Mar-2008 19:04:46,23-Mar-2008 19:04:47,12,1,2008-03-23 19:04:46,2008-03-23 19:04:47,1.0,0

In [5]:
df.loc[(df['A'].dt.day==d) & (df['A'].dt.month==m)& (df['A'].dt.year==yr), 'day'] = 1
day_df= df.loc[df['day']==1]
day_df

,start,end,id,val,A,B,time,count,day
1189,21-Mar-2008 0:00:11,21-Mar-2008 0:00:12,24,1,2008-03-21 00:00:11,2008-03-21 00:00:12,1.0,0,1.0
1190,21-Mar-2008 3:49:47,21-Mar-2008 3:49:48,24,1,2008-03-21 03:49:47,2008-03-21 03:49:48,1.0,0,1.0
1191,21-Mar-2008 3:49:54,21-Mar-2008 3:50:45,6,1,2008-03-21 03:49:54,2008-03-21 03:50:45,51.0,0,1.0
1192,21-Mar-2008 3:49:58,21-Mar-2008 3:50:50,24,1,2008-03-21 03:49:58,2008-03-21 03:50:50,52.0,0,1.0
1193,21-Mar-2008 3:50:40,21-Mar-2008 3:50:41,14,1,2008-03-21 03:50:40,2008-03-21 03:50:41,1.0,0,1.0
1194,21-Mar-2008 8:30:54,21-Mar-2008 8:31:44,24,1,2008-03-21 08:30:54,2008-03-21 08:31:44,50.0,0,1.0
1195,21-Mar-2008 8:31:00,21-Mar-2008 8:31:03,6,1,2008-03-21 08:31:00,2008-03-21 08:31:03,3.0,0,1.0
1196,21-Mar-2008 8:31:25,21-Mar-2008 8:31:26,14,1,2008-03-21 08:31:25,2008-03-21 08:31:26,1.0,0,1.0
1197,21-Mar-2008 8:31:28,21-Mar-2008 8:31:31,6,1,2008-03-21 08:31:28,2008-03-21 08:31:31,3.0,0,1.0
1198,21-Mar-2008 9:04:21,21-Mar-2008 9:04:22,24,1,2008-03-21 09:04:21,2008-03-21 09:04:22,1.0,0,1.0
1199,21-Mar-2008 9:04:26,21-Mar-2008 17:03:51,24,1,2008-03-21 09:04:26,2008-03-21 17:03:51,28765.0,0,1.0
1200,21-Mar-2008 9:13:25,21-Mar-2008 9:13:29,6,1,2008-03-21 09:13:25,2008-03-21 09:13:29,4.0,0,1.0
1201,21-Mar-2008 9:14:19,21-Mar-2008 9:14:20,14,1,2008-03-21 09:14:19,2008-03-21 09:14:20,1.0,0,1.0
1202,21-Mar-2008 9:14:25,21-Mar-2008 9:15:18,6,1,2008-03-21 09:14:25,2008-03-21 09:15:18,53.0,0,1.0
1203,21-Mar-2008 9:17:57,21-Mar-2008 9:17:59,5,1,2008-03-21 09:17:57,2008-03-21 09:17:59,2.0,0,1.0
1204,21-Mar-2008 9:24:18,21-Mar-2008 9:24:19,5,1,2008-03-21 09:24:18,2008-03-21 09:24:19,1.0,0,1.0
1205,21-Mar-2008 9:24:23,21-Mar-2008 15:51:49,5,1,2008-03-21 09:24:23,2008-03-21 15:51:49,23246.0,0,1.0
1206,21-Mar-2008 9:42:35,21-Mar-2008 9:42:39,12,1,2008-03-21 09:42:35,2008-03-21 09:42:39,4.0,0,1.0
1207,21-Mar-2008 15:50:16,21-Mar-2008 15:50:20,12,1,2008-03-21 15:50:16,2008-03-21 15:50:20,4.0,0,1.0
1208,21-Mar-2008 15:52:04,21-Mar-2008 15:52:08,6,1,2008-03-21 15:52:04,2008-03-21 15:52:08,4.0,0,1.0
1209,21-Mar-2008 15:52:54,21-Mar-2008 15:52:55,14,1,2008-03-21 15:52:54,2008-03-21 15:52:55,1.0,0,1.0
1210,21-Mar-2008 15:52:54,21-Mar-2008 15:53:05,6,1,2008-03-21 15:52:54,2008-03-21 15:53:05,11.0,0,1.0
1211,21-Mar-2008 15:53:03,21-Mar-2008 15:53:11,5,1,2008-03-21 15:53:03,2008-03-21 15:53:11,8.0,0,1.0
1212,21-Mar-2008 15:54:06,21-Mar-2008 18:24:28,5,1,2008-03-21 15:54:06,2008-03-21 18:24:28,9022.0,0,1.0
1213,21-Mar-2008 15:57:07,21-Mar-2008 15:58:06,23,1,2008-03-21 15:57:07,2008-03-21 15:58:06,59.0,0,1.0
1214,21-Mar-2008 15:57:52,21-Mar-2008 15:57:56,8,1,2008-03-21 15:57:52,2008-03-21 15:57:56,4.0,0,1.0
1215,21-Mar-2008 17:03:54,21-Mar-2008 17:03:55,24,1,2008-03-21 17:03:54,2008-03-21 17:03:55,1.0,0,1.0
1216,21-Mar-2008 17:06:52,21-Mar-2008 17:06:53,24,1,2008-03-21 17:06:52,2008-03-21 17:06:53,1.0,0,1.0
1217,21-Mar-2008 17:06:57,21-Mar-2008 17:08:12,24,1,2008-03-21 17:06:57,2008-03-21 17:08:12,75.0,0,1.0
1218,21-Mar-2008 18:05:09,21-Mar-2008 18:05:10,24,1,2008-03-21 18:05:09,2008-03-21 18:05:10,1.0,0,1.0
1219,21-Mar-2008 18:24:31,21-Mar-2008 18:24:32,5,1,2008-03-21 18:24:31,2008-03-21 18:24:32,1.0,0,1.0
1220,21-Mar-2008 18:24:38,21-Mar-2008 18:24:39,5,1,2008-03-21 18:24:38,2008-03-21 18:24:39,1.0,0,1.0
1221,21-Mar-2008 18:24:50,21-Mar-2008 18:24:51,5,1,2008-03-21 18:24:50,2008-03-21 18:24:51,1.0,0,1.0
1222,21-Mar-2008 18:25:15,21-Mar-2008 18:25:16,6,1,2008-03-21 18:25:15,2008-03-21 18:25:16,1.0,0,1.0
1223,21-Mar-2008 18:27:46,21-Mar-2008 18:27:56,8,1,2008-03-21 18:27:46,2008-03-21 18:27:56,10.0,0,1.0
1224,21-Mar-2008 18:27:57,21-Mar-2008 18:27:58,8,1,2008-03-21 18:27:57,2008-03-21 18:27:58,1.0,0,1.0
1225,21-Mar-2008 18:28:00,21-Mar-2008 18:28:01,8,1,2008-03-21 18:28:00,2008-03-21 18:28:01,1.0,0,1.0
1226,21-Mar-2008 18:28:19,21-Mar-2008 18:28:20,17,1,2008-03-21 18:28:19,2008-03-21 18:28:20,1.0,0,1.0
1227,21-Mar-2008 19:11:10,21-Mar-2008 19:11:14,12,1,2008-03-21 19:11:10,2008-03-21 19:11:14,4.0,0,1.0

In [6]:
arr = np.zeros((25,), dtype='float64')

In [7]:
for index, row in day_df.iterrows():
    arr[row['id']]+=row['time']

In [14]:
def humanize_time(secs):
    mins, secs = divmod(secs, 60)
    hours, mins = divmod(mins, 60)
    return '%02d hours %02d minutes %02d seconds' % (hours, mins, secs)

In [15]:
index = np.zeros((24,1),dtype='int64')
j=0
for i in range(1,24):
    print (humanize_time(arr[i].astype('int')))
    if(arr[i]!=0):
        index[j]=i
        j+=1

00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
08 hours 58 minutes 02 seconds
00 hours 02 minutes 10 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 16 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 12 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 04 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 01 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 00 seconds
00 hours 00 minutes 59 seconds

In [16]:
count = day_df.groupby('id').count()

In [17]:
array = count['time']
array

id
5      8
6      8
8      4
12     3
14     4
17     1
23     1
24    10
Name: time, dtype: int64

In [50]:
print ("ID\tFrequency\tTime\t\t\t\tDate\t\tName")
for j in range(0,24):
    if(index[j]!=0):
        i=index[j][0]
        print (str(i)+"\t"+str(count['count'][i])+'\t\t'+humanize_time(arr[i].astype('int'))+'\t'+str(d)+'/'+str(m)+'/'+str(yr)+'\t'+dict[i])

ID	Frequency	Time				Date		Name
5	8		08 hours 58 minutes 02 seconds	21/3/2008	Hall-Toilet door
6	8		00 hours 02 minutes 10 seconds	21/3/2008	Hall-Bathroom door
8	4		00 hours 00 minutes 16 seconds	21/3/2008	Fridge
12	3		00 hours 00 minutes 12 seconds	21/3/2008	Frontdoor
14	4		00 hours 00 minutes 04 seconds	21/3/2008	ToiletFlush
17	1		00 hours 00 minutes 01 seconds	21/3/2008	Freezer
23	1		00 hours 00 minutes 59 seconds	21/3/2008	Groceries cupboard